### ISSUE TITLE
How to run on Windows 10?

### ISSUE THREAD

**Issue by tuandesu** [zupzup/rust-fullstack-example#1]
I installed GnuWin32 and MinGW on Windows, then run "make dev" command for backend --> it run OK.
But when I try with "make web" command for frontend, it shown err:
---------------------------
C:\Projects\Rust\rust_fullstack_exp\frontend>make web
'RUSTFLAGS' is not recognized as an internal or external command,
operable program or batch file.
make: *** [web] エラー 1

**Comment by zupzup** [comment]
Hello

The Makefile will only work on UNIX systems unfortunately.

However, you can try to just delete the `RUSTFLAGS=` part of the command in both `make build` and `make web` and see if it works, this is just an override, if you have any custom cargo flags set (e.g. for using lld)
